In [4]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [6]:
fake = Faker()

In [21]:
occupations = [
  'Software Engineer', 'Teacher', 'Doctor', 'Nurse', 'Accountant', 'Salesperson',
    'Manager', 'Driver', 'Clerk', 'Electrician', 'Mechanic', 'Chef', 'Artist',
    'Scientist', 'Lawyer', 'Police Officer', 'Pharmacist', 'Consultant', 'Analyst', 'Farmer'
]

def generate_row_with_nulls():
  age = random.randint(15,60)
  income = random.randint(15000,100000)
  max_budget = min(income,200000)
  min_budget = 50000

  if max_budget < min_budget:
    budget = max_budget
  else:
    budget = random.randint(min_budget,max_budget)
  ph_no = fake.phone_number()if np.random.rand() > 0.1 else None
  mail_id = fake.email()if np.random.rand() > 0.1 else None
  rented_house = random.choice(['Yes','No'])
  insurance =  random.choice(['Yes','No'])
  occupation = random.choice(occupations)

  return [age,income,budget,ph_no,mail_id,rented_house,insurance,occupation]

num_rows = 10000

data = [generate_row_with_nulls() for _ in range(num_rows)]

columns = ['age','income','budget','ph_no','mail_id','rented_house','insurance','occupation']

df = pd.DataFrame(data,columns = columns)

In [22]:
df.shape

(10000, 8)

In [23]:
df.head()

,age,income,budget,ph_no,mail_id,rented_house,insurance,occupation
0,56,89404,66540,001-638-984-9859x09716,None,Yes,Yes,Consultant
1,29,60698,58178,None,lancethompson@example.org,Yes,No,Analyst
2,44,63323,57908,None,jessicawatkins@example.net,Yes,No,Doctor
3,54,36318,36318,(765)626-7616x87431,None,Yes,Yes,Mechanic
4,54,71810,50045,800-409-5643x331,frenchkatherine@example.com,Yes,No,Software Engineer

In [24]:
df.tail()

,age,income,budget,ph_no,mail_id,rented_house,insurance,occupation
9995,40,21126,21126,2117592886,mariawright@example.com,Yes,No,Artist
9996,52,70511,65924,None,None,No,No,Teacher
9997,51,50906,50798,363-632-0442,melissadavis@example.com,Yes,No,Chef
9998,20,83507,83490,207.759.4322,stephanie93@example.net,No,No,Software Engineer
9999,37,18003,18003,558.496.4844x477,None,Yes,No,Manager

In [25]:
df.info

<bound method DataFrame.info of       age  income  budget                   ph_no  \
0      56   89404   66540  001-638-984-9859x09716
1      29   60698   58178                    None
2      44   63323   57908                    None
3      54   36318   36318     (765)626-7616x87431
4      54   71810   50045        800-409-5643x331
...   ...     ...     ...                     ...
9995   40   21126   21126              2117592886
9996   52   70511   65924                    None
9997   51   50906   50798            363-632-0442
9998   20   83507   83490            207.759.4322
9999   37   18003   18003        558.496.4844x477

                          mail_id rented_house insurance         occupation
0                            None          Yes       Yes         Consultant
1       lancethompson@example.org          Yes        No            Analyst
2      jessicawatkins@example.net          Yes        No             Doctor
3                            None          Yes       Yes           Mechanic
4     frenchkatherine@example.com          Yes        No  Software Engineer
...                           ...          ...       ...                ...
9995      mariawright@example.com          Yes        No             Artist
9996                         None           No        No            Teacher
9997     melissadavis@example.com          Yes        No               Chef
9998      stephanie93@example.net           No        No  Software Engineer
9999                         None          Yes        No            Manager

[10000 rows x 8 columns]>

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           10000 non-null  int64
 1   income        10000 non-null  int64
 2   budget        10000 non-null  int64
 3   ph_no         8937 non-null   object
 4   mail_id       8985 non-null   object
 5   rented_house  10000 non-null  object
 6   insurance     10000 non-null  object
 7   occupation    10000 non-null  object
dtypes: int64(3), object(5)
memory usage: 625.1+ KB

In [27]:
df.describe()

                age        income        budget
count  10000.000000  10000.000000  10000.000000
mean      37.559500  57719.447700  50246.894000
std       13.227772  24601.362737  18238.602202
min       15.000000  15010.000000  15010.000000
25%       26.000000  36022.250000  36022.250000
50%       38.000000  57751.000000  51742.500000
75%       49.000000  79281.750000  61708.250000
max       60.000000  99996.000000  99288.000000

In [28]:
df.isna().sum()

age                0
income             0
budget             0
ph_no           1063
mail_id         1015
rented_house       0
insurance          0
occupation         0
dtype: int64